apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "continuum-ai.fullname" . }}-config
  labels:
    {{- include "continuum-ai.labels" . | nindent 4 }}
data:
  NODE_ENV: production
  INFRA_ENABLED: "true"
  SWAGGER_ENABLED: "false"
  REDIS_MODE: cluster
  REDIS_CLUSTER_NODES: "{{ range $index, $_ := until (int .Values.redis.replicas) }}{{ if $index }},{{ end }}{{ include "continuum-ai.fullname" $ }}-redis-{{ $index }}.{{ include "continuum-ai.fullname" $ }}-redis-headless:{{ $.Values.redis.port }}{{ end }}"
  REDIS_PORT: {{ .Values.redis.port | quote }}
  BULLMQ_PREFIX: continuum
  MONGODB_AUTO_INDEX: "false"
  AUDIT_DATABASE: continuum_audit
